"use client";

/**
 * DraftPreview — Displays the AI-generated document text with disclaimer,
 * and a button to download as PDF.
 */

import { useState } from "react";
import { exportDraftPdf } from "@/lib/api";

interface Props {
  draftText: string;
  disclaimer: string;
  documentType: string;
}

export default function DraftPreview({
  draftText,
  disclaimer,
  documentType,
}: Props) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const handleDownload = async () => {
    setIsExporting(true);
    setExportError(null);

    try {
      const blob = await exportDraftPdf({
        document_type: documentType,
        draft_text: draftText,
      });

      // Create download link
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const typeSlug = documentType.replace(/_/g, "-");
      const timestamp = new Date().toISOString().slice(0, 10);
      a.download = `lexindia-${typeSlug}-${timestamp}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err: any) {
      console.error("PDF export failed:", err);
      setExportError("Failed to generate PDF. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-fade-up">
      {/* Disclaimer Banner */}
      <div className="px-5 py-4 rounded-xl bg-red-500/8 border border-red-500/20">
        <div className="flex items-start gap-3">
          <span className="text-lg mt-0.5">⚠️</span>
          <p className="text-sm text-red-300 leading-relaxed font-medium">
            {disclaimer}
          </p>
        </div>
      </div>

      {/* Document Preview */}
      <div className="glass-card p-8">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-lg font-display font-semibold text-surface-50 flex items-center gap-2">
            <span>📄</span> Document Preview
          </h3>
          <span className="text-xs text-surface-500 bg-surface-800 px-3 py-1 rounded-full">
            AI Generated
          </span>
        </div>

        {/* Document Content */}
        <div className="bg-white/[0.03] border border-surface-700/30 rounded-xl p-6 sm:p-8">
          <div className="prose prose-invert max-w-none">
            {draftText.split("\n").map((line, i) => {
              const trimmed = line.trim();
              if (!trimmed) return <br key={i} />;

              // Render ALL CAPS as headings
              if (trimmed === trimmed.toUpperCase() && trimmed.length < 80 && trimmed.length > 2) {
                return (
                  <h3
                    key={i}
                    className="text-base font-bold text-surface-100 mt-4 mb-2 uppercase tracking-wide"
                  >
                    {trimmed}
                  </h3>
                );
              }

              // Render separators
              if (trimmed.startsWith("---") || trimmed.startsWith("___")) {
                return <hr key={i} className="border-surface-700/30 my-4" />;
              }

              // Regular paragraph
              return (
                <p
                  key={i}
                  className="text-sm text-surface-300 leading-relaxed mb-1.5"
                >
                  {trimmed}
                </p>
              );
            })}
          </div>
        </div>
      </div>

      {/* Export Error */}
      {exportError && (
        <div className="px-5 py-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
          {exportError}
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4">
        <button
          onClick={handleDownload}
          disabled={isExporting}
          className="btn-primary flex-1 text-center py-4 text-lg disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isExporting ? (
            <span className="flex items-center justify-center gap-3">
              <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating PDF...
            </span>
          ) : (
            "📥 Download as PDF"
          )}
        </button>
        <button
          onClick={() => {
            navigator.clipboard.writeText(draftText);
          }}
          className="btn-secondary flex-1 text-center py-4 text-lg"
        >
          📋 Copy Text
        </button>
      </div>

      {/* Footer Note */}
      <p className="text-xs text-surface-500 text-center leading-relaxed">
        Generated by LexIndia — For reference only. Not a substitute for legal advice.
        <br />
        PDFs are generated on-the-fly and are never stored on our servers.
      </p>
    </div>
  );
}
